### INDEX Activities
GET http://localhost:3000/activities.json

### CREATE Activities
POST http://localhost:3000/activities.json
Content-Type: application/json

{
  "name": "The Bean",
  "address": "201 E Randolph St"
}

### SHOW Activities
GET http://localhost:3000/activities/2.json

### Mapbox Token
GET http://localhost:3000/mapbox_token.json

### INDEX Markers
GET http://localhost:3000/markers.json

### SHOW Markers
GET http://localhost:3000/markers/:id.json

### CREATE Markers
POST http://localhost:3000/markers.json

### CREATE Users (signup)
POST http://localhost:3000/users.json
Content-Type: application/json

{
  "name": "Test name",
  "email": "test@test.com",
  "password": "password",
  "password_confirmation": "password"
}

### CREATE Sessions (login)
POST http://localhost:3000/sessions.json
Content-Type: application/json

{
  "email": "test@test.com",
  "password": "password"
}